class Labels:
    TEXT = 'text'
    HW_TEXT = 'hw text'
    EMPTY_TEXT = 'empty-text'
    FLOATING_NAME = 'floating name'
    FLOATING_DATE = 'floating date'
    FLOATING_ADDRESS = 'floating address'
    FLOATING_PHONE = 'floating phone'
    FLOATING_EMAIL = 'floating email'
    FLOATING_YEAR = 'floating year'
    FLOATING_DOCUMENT_TYPE = 'floating document type'
    FLOATING_DOCUMENT_TITLE = 'floating document title'
    FLOATING_TEXT = 'floating text'
    FLOATING_WEBSITE = 'floating website'
    UNVALUED_KEY = 'unvalued_key'

class DepricatedLabels:
    IGNORE_ZONE = 'ignore-zone'
    TABLE = 'table'
    CHECKBOX_SELECTED = 'check-box_selected'
    CHECKBOX_UNSELECTED = 'check-box_unselected'
    SECTION = 'section'
